server:
  port: 9070
  servlet:
    context-path: /api

spring:
  application:
    name: employee-service
  profiles:
    active: dev
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;instanceName=SQLEXPRESS;databaseName=employee_service
    username: sa
    password: Hasani97#
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  boot:
    admin:
      client:
        instance:
          service-base-url: http://localhost:8888
        #url: http://localhost:8888
        username: admin
        password: admin
  cloud:
    stream:
      bindings:
        employee-producer:
          destination: employeeOut
      default:
        contentType: application/json
    config:
      uri: http://localhost:8191
      enabled: true

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: ${server.servlet.context-path}/actuator/info
    healthCheckUrlPath: ${server.servlet.context-path}/actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart

management:
  endpoints:
    web:
      #Enable All Actuator endpoints except shutdown
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    #Not Recommended / Demo purpose
    shutdown:
      enabled: true

#Show Tags per Instance
info:
  tags:
    Name : ${spring.application.name}
    Environment : ${spring.profiles.active}

logging:
  file:
    path: /logs


